package ca.ulaval.glo2004.gui;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class MainWindow {
    public JPanel rootPanel;
    private JPanel propertiesPanel;
    private JPanel rightPanel;
    private JPanel controlPanel;
    private JPanel mainPanel;
    private JPanel buttonsPanel;
    private JButton btnSave;
    private JButton btnUndo;
    private JButton btnRedo;
    private JButton btnGrille;
    private JButton btnFenetre;
    private JButton btnPorte;
    private JButton btnPrise;
    private JButton btnRetourAir;
    private JButton btnSupprimer;
    private JPanel DimensionsPanel;
    private JButton btnDimensionsCollapse;
    private JPanel dimensionPanelContent;
    private JPanel dimLargeurPanel;
    private JTextField tbLargeur;
    private JTextField tbProfondeur;
    private JTextField tbHauteur;
    private JTextField tbEpaisseurMurs;
    private JTextField tbLargeurPli;
    private JTextField tbPliSoudure;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public MainWindow() {
        btnDimensionsCollapse.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                boolean isActivated = !dimensionPanelContent.isVisible();
                dimensionPanelContent.setVisible(isActivated);
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
